DATABASE_URI = 'mysql+pymysql://root:admin@localhost:3306/exception_database'